services:
  openvpn:
    image: ghcr.io/kafouche/openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    # dns:
    #   - 9.9.9.9
    #   - 1.1.1.1
    #   - 149.112.112.112
    #   - 1.0.0.1
    name: "openvpn"
    network_mode: bridge
    # ports:
    #   - "xxxx:xxxx/tcp" # Those are the ports the `client-service' is using.
    restart: "unless-stopped"
    volumes:
      - type: bind
        read_only: true
        source: "./config/"
        target: "/etc/openvpn/"

  # client-service:
  #   image: "..."
  #   depends_on:
  #     - openvpn
  #   network_mode: "service:openvpn"
  #   restart: unless-stopped
  #   ...
    